< POST /restore/ HTTP/1.1
< Host: 127.0.0.1:8274
< User-Agent: python-requests/2.25.1
< Accept-Encoding: gzip, deflate
< Accept: */*
< Connection: keep-alive
< Content-Length: 308
< Content-Type: application/json
< 
< {"backup_id": 2147483648, "name": "KnjPLQzQZoLYTSHuqEIVHuybIGasCHIIkkojFoSAujfjMrBtDvguKQOSOAnflmKskRgMFENaLRZiTdQGkAlmdeWdFgAuompNmFALFnEjcazFwivJxvhxfwZiItCbpXYPsHplWtpvauRsWNVOhRzsENFJTrQcBIDaYKpxweyJvRHOfVTUwvfLFpyhYhOakXTJYWUwIcujUbXwyBhyseYhBZKuLDqHODDUNgtcQtEVSPMasvfaTaZohlUqsqYDUPOr", "timeout": -1}
> HTTP/1.1 422 Unprocessable Entity
> Date: Wed, 14 Apr 2021 15:41:12 GMT
> Server: Apache/2.4.38 (Debian)
> X-Powered-By: PHP/8.0.3
> Cache-Control: no-cache, private
> Content-Length: 158
> Keep-Alive: timeout=5, max=100
> Connection: Keep-Alive
> Content-Type: application/json
> 
{"name":["The name may not be greater than 255 characters."],"timeout":["The timeout must be at least 0."],"backup_id":["The selected backup id is invalid."]}